# 公共配置文件
spring:   # swagger3
  #mvc.pathmatch.matching-strategy=ant_path_matcher
  application:
    name: yuepei-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuepei_db?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 1
  # 邮箱配置
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 25
    username: xxx@qq.com # 发件人
    password:  # IMAP 密码
    from: xxx@qq.com # 发件邮箱

server:
  port: 8122
  servlet:
    context-path: /api
    session:
      cookie:
        domain: yp.jishuqin.cn
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



